SET statement_timeout = 0;
SET lock_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;
SET default_tablespace = '';
SET default_table_access_method = heap;

CREATE TABLE IF NOT EXISTS public.event_publication
(
    id                     uuid                             NOT NULL,
    completion_attempts    integer                          NOT NULL,
    completion_date        timestamp(6) with time zone,
    event_type             character varying(255),
    last_resubmission_date timestamp(6) with time zone,
    listener_id            character varying(255),
    publication_date       timestamp(6) with time zone,
    serialized_event       character varying(255),
    status                 character varying(255),
    CONSTRAINT event_publication_pkey PRIMARY KEY (id),
    CONSTRAINT event_publication_status_check CHECK (
        status::text = ANY (
            ARRAY['PUBLISHED', 'PROCESSING', 'COMPLETED', 'FAILED', 'RESUBMITTED']::text[]
        )
    )
);

CREATE TABLE IF NOT EXISTS public.modules
(
    id_module bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name      character varying(50)                  NOT NULL,
    CONSTRAINT modules_pkey PRIMARY KEY (id_module),
    CONSTRAINT uk_modules_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.roles
(
    id_role bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name    character varying(20),
    CONSTRAINT roles_pkey PRIMARY KEY (id_role),
    CONSTRAINT uk_roles_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.scopes
(
    id_scope    bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        character varying(80)                  NOT NULL,
    description character varying(255),
    CONSTRAINT scopes_pkey PRIMARY KEY (id_scope),
    CONSTRAINT uk_scopes_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.submodules
(
    id_submodule bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         character varying(50),
    id_module    bigint,
    CONSTRAINT submodules_pkey PRIMARY KEY (id_submodule),
    CONSTRAINT uk_submodules_name_module UNIQUE (name, id_module),
    CONSTRAINT fk_submodules_module FOREIGN KEY (id_module) REFERENCES public.modules (id_module)
);

CREATE TABLE IF NOT EXISTS public.submodule_required_scopes
(
    id_submodule bigint NOT NULL,
    id_scope     bigint NOT NULL,
    CONSTRAINT submodule_required_scopes_pkey PRIMARY KEY (id_submodule, id_scope),
    CONSTRAINT fk_submodule_required_scopes_submodule FOREIGN KEY (id_submodule) REFERENCES public.submodules (id_submodule),
    CONSTRAINT fk_submodule_required_scopes_scope FOREIGN KEY (id_scope) REFERENCES public.scopes (id_scope)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id_user  bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username character varying(60),
    email    character varying(100),
    enabled  boolean,
    password character varying(100),
    is_admin boolean,
    CONSTRAINT users_pkey PRIMARY KEY (id_user),
    CONSTRAINT uk_users_username UNIQUE (username),
    CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public.role_scopes
(
    id_role  bigint NOT NULL,
    id_scope bigint NOT NULL,
    CONSTRAINT role_scopes_pkey PRIMARY KEY (id_role, id_scope),
    CONSTRAINT fk_role_scopes_role FOREIGN KEY (id_role) REFERENCES public.roles (id_role),
    CONSTRAINT fk_role_scopes_scope FOREIGN KEY (id_scope) REFERENCES public.scopes (id_scope)
);

CREATE TABLE IF NOT EXISTS public.user_scope_grants
(
    id_user_scope_grant bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_user             bigint                                  NOT NULL,
    id_scope            bigint                                  NOT NULL,
    granted_by          bigint,
    reason              character varying(255),
    expires_at          timestamp(6) with time zone,
    created_at          timestamp(6) with time zone             NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT user_scope_grants_pkey PRIMARY KEY (id_user_scope_grant),
    CONSTRAINT fk_user_scope_grants_user FOREIGN KEY (id_user) REFERENCES public.users (id_user),
    CONSTRAINT fk_user_scope_grants_scope FOREIGN KEY (id_scope) REFERENCES public.scopes (id_scope),
    CONSTRAINT fk_user_scope_grants_granted_by FOREIGN KEY (granted_by) REFERENCES public.users (id_user)
);

CREATE TABLE IF NOT EXISTS public.users_modules
(
    id_user   bigint NOT NULL,
    id_module bigint NOT NULL,
    CONSTRAINT users_modules_pkey PRIMARY KEY (id_user, id_module),
    CONSTRAINT fk_users_modules_user FOREIGN KEY (id_user) REFERENCES public.users (id_user),
    CONSTRAINT fk_users_modules_module FOREIGN KEY (id_module) REFERENCES public.modules (id_module)
);

CREATE TABLE IF NOT EXISTS public.users_roles
(
    id_user bigint NOT NULL,
    id_role bigint NOT NULL,
    CONSTRAINT users_roles_pkey PRIMARY KEY (id_user, id_role),
    CONSTRAINT fk_users_roles_user FOREIGN KEY (id_user) REFERENCES public.users (id_user),
    CONSTRAINT fk_users_roles_role FOREIGN KEY (id_role) REFERENCES public.roles (id_role)
);

CREATE TABLE IF NOT EXISTS public.users_submodules
(
    id_user      bigint NOT NULL,
    id_submodule bigint NOT NULL,
    CONSTRAINT users_submodules_pkey PRIMARY KEY (id_user, id_submodule),
    CONSTRAINT fk_users_submodules_user FOREIGN KEY (id_user) REFERENCES public.users (id_user),
    CONSTRAINT fk_users_submodules_submodule FOREIGN KEY (id_submodule) REFERENCES public.submodules (id_submodule)
);
