SET
statement_timeout = 0;
SET
lock_timeout = 0;

SET
transaction_timeout = 0;
SET
client_encoding = 'UTF8';
SET
standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET
check_function_bodies = false;
SET
xmloption = content;
SET
client_min_messages = warning;
SET
row_security = off;

SET
default_tablespace = '';

SET
default_table_access_method = heap;



CREATE TABLE public.event_publication
(
    id                     uuid    NOT NULL,
    completion_attempts    integer NOT NULL,
    completion_date        timestamp(6) with time zone,
    event_type             character varying(255),
    last_resubmission_date timestamp(6) with time zone,
    listener_id            character varying(255),
    publication_date       timestamp(6) with time zone,
    serialized_event       character varying(255),
    status                 character varying(255),
    CONSTRAINT event_publication_status_check CHECK (((status)::text = ANY ((ARRAY['PUBLISHED':: character varying, 'PROCESSING':: character varying, 'COMPLETED':: character varying, 'FAILED':: character varying, 'RESUBMITTED':: character varying])::text[])
) )
);



CREATE TABLE public.modules
(
    id_module bigint                NOT NULL,
    name      character varying(50) NOT NULL
);



ALTER TABLE public.modules ALTER COLUMN id_module ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.modules_id_module_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE public.roles
(
    id_role bigint NOT NULL,
    name    character varying(20)
);



ALTER TABLE public.roles ALTER COLUMN id_role ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_id_role_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE public.submodules
(
    id_submodule bigint NOT NULL,
    name         character varying(50),
    id_module    bigint
);



ALTER TABLE public.submodules ALTER COLUMN id_submodule ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.submodules_id_submodule_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE public.users
(
    id_user  bigint NOT NULL,
    email    character varying(50),
    enabled  boolean,
    is_admin boolean,
    password character varying(100),
    username character varying(40),
    CONSTRAINT users_id_user_check CHECK (((id_user >= 1) AND (id_user <= 999999999)))
);



ALTER TABLE public.users ALTER COLUMN id_user ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_user_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE public.users_modules
(
    id_user   bigint NOT NULL,
    id_module bigint NOT NULL
);



CREATE TABLE public.users_roles
(
    id_user bigint NOT NULL,
    id_role bigint NOT NULL
);



CREATE TABLE public.users_submodules
(
    id_user      bigint NOT NULL,
    id_submodule bigint NOT NULL
);



ALTER TABLE ONLY public.event_publication
    ADD CONSTRAINT event_publication_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.modules
    ADD CONSTRAINT modules_pkey PRIMARY KEY (id_module);



ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id_role);



ALTER TABLE ONLY public.submodules
    ADD CONSTRAINT submodules_pkey PRIMARY KEY (id_submodule);



ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk_users_email UNIQUE (email);



ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk_users_id_username UNIQUE (id_user, username);



ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk_users_username UNIQUE (username);



ALTER TABLE ONLY public.modules
    ADD CONSTRAINT ukn5ng23nwasusfsyqk68hx5a05 UNIQUE (name);



ALTER TABLE ONLY public.roles
    ADD CONSTRAINT ukofx66keruapi6vyqpv6f2or37 UNIQUE (name);



ALTER TABLE ONLY public.submodules
    ADD CONSTRAINT ukpy6c988d8ndhisbf6u0upehx6 UNIQUE (name, id_module);



ALTER TABLE ONLY public.users_modules
    ADD CONSTRAINT users_modules_pkey PRIMARY KEY (id_user, id_module);



ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id_user);



ALTER TABLE ONLY public.users_roles
    ADD CONSTRAINT users_roles_pkey PRIMARY KEY (id_user, id_role);



ALTER TABLE ONLY public.users_submodules
    ADD CONSTRAINT users_submodules_pkey PRIMARY KEY (id_user, id_submodule);



ALTER TABLE ONLY public.users_roles
    ADD CONSTRAINT fk3avenccqsoqwrfur1hb8mpbrw FOREIGN KEY (id_role) REFERENCES public.roles(id_role);



ALTER TABLE ONLY public.users_roles
    ADD CONSTRAINT fk6ywr92flw5416dup8uc2egb83 FOREIGN KEY (id_user) REFERENCES public.users(id_user);



ALTER TABLE ONLY public.users_modules
    ADD CONSTRAINT fk7tsj8e6yync1d9bxakrg8l1qv FOREIGN KEY (id_user) REFERENCES public.users(id_user);



ALTER TABLE ONLY public.users_submodules
    ADD CONSTRAINT fkimk439a9luqpd61x1bmk5ghs8 FOREIGN KEY (id_submodule) REFERENCES public.submodules(id_submodule);



ALTER TABLE ONLY public.users_modules
    ADD CONSTRAINT fkm0mxqx5ql39jau89vg67ulmjn FOREIGN KEY (id_module) REFERENCES public.modules(id_module);



ALTER TABLE ONLY public.users_submodules
    ADD CONSTRAINT fkp40okk64mkhv1vm3hjxnsccts FOREIGN KEY (id_user) REFERENCES public.users(id_user);



ALTER TABLE ONLY public.submodules
    ADD CONSTRAINT fks3of0v8tl1wt6mju1pt2qtrhw FOREIGN KEY (id_module) REFERENCES public.modules(id_module);





