CREATE TABLE IF NOT EXISTS public.scopes
(
    id_scope    bigint                NOT NULL,
    name        character varying(80) NOT NULL,
    description character varying(255)
);

ALTER TABLE public.scopes ALTER COLUMN id_scope ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.scopes_id_scope_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.scopes
    ADD CONSTRAINT scopes_pkey PRIMARY KEY (id_scope);

ALTER TABLE ONLY public.scopes
    ADD CONSTRAINT uk_scopes_name UNIQUE (name);

CREATE TABLE IF NOT EXISTS public.role_scopes
(
    id_role  bigint NOT NULL,
    id_scope bigint NOT NULL
);

ALTER TABLE ONLY public.role_scopes
    ADD CONSTRAINT role_scopes_pkey PRIMARY KEY (id_role, id_scope);

ALTER TABLE ONLY public.role_scopes
    ADD CONSTRAINT fk_role_scopes_role FOREIGN KEY (id_role) REFERENCES public.roles(id_role);

ALTER TABLE ONLY public.role_scopes
    ADD CONSTRAINT fk_role_scopes_scope FOREIGN KEY (id_scope) REFERENCES public.scopes(id_scope);

CREATE TABLE IF NOT EXISTS public.user_scope_grants
(
    id_user_scope_grant bigint                   NOT NULL,
    id_user             bigint                   NOT NULL,
    id_scope            bigint                   NOT NULL,
    granted_by          bigint,
    reason              character varying(255),
    expires_at          timestamp(6) with time zone,
    created_at          timestamp(6) with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE public.user_scope_grants ALTER COLUMN id_user_scope_grant ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_scope_grants_id_user_scope_grant_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.user_scope_grants
    ADD CONSTRAINT user_scope_grants_pkey PRIMARY KEY (id_user_scope_grant);

ALTER TABLE ONLY public.user_scope_grants
    ADD CONSTRAINT fk_user_scope_grants_user FOREIGN KEY (id_user) REFERENCES public.users(id_user);

ALTER TABLE ONLY public.user_scope_grants
    ADD CONSTRAINT fk_user_scope_grants_scope FOREIGN KEY (id_scope) REFERENCES public.scopes(id_scope);

ALTER TABLE ONLY public.user_scope_grants
    ADD CONSTRAINT fk_user_scope_grants_granted_by FOREIGN KEY (granted_by) REFERENCES public.users(id_user);

INSERT INTO scopes (name, description)
VALUES ('user:read', 'Read users'),
       ('user:create', 'Create users'),
       ('user:update', 'Update users'),
       ('user:delete', 'Delete users'),
       ('perfume:read', 'Read perfumes'),
       ('perfume:create', 'Create perfumes'),
       ('perfume:update', 'Update perfumes'),
       ('perfume:delete', 'Delete perfumes') ON CONFLICT (name) DO NOTHING;

INSERT INTO role_scopes (id_role, id_scope)
SELECT r.id_role, s.id_scope
FROM roles r
CROSS JOIN scopes s
WHERE r.name = 'ADMIN' ON CONFLICT (id_role, id_scope) DO NOTHING;

INSERT INTO role_scopes (id_role, id_scope)
SELECT r.id_role, s.id_scope
FROM roles r
JOIN scopes s ON s.name = 'user:read'
WHERE r.name = 'USER' ON CONFLICT (id_role, id_scope) DO NOTHING;

INSERT INTO user_scope_grants (id_user, id_scope, reason)
SELECT u.id_user, s.id_scope, 'legacy users read access'
FROM users u
JOIN users_modules um ON um.id_user = u.id_user
JOIN modules m ON m.id_module = um.id_module AND m.name = 'USERS'
JOIN users_submodules us ON us.id_user = u.id_user
JOIN submodules sm ON sm.id_submodule = us.id_submodule AND sm.name = 'READUSERS'
JOIN scopes s ON s.name = 'user:read'
WHERE NOT EXISTS (
    SELECT 1
    FROM user_scope_grants existing
    WHERE existing.id_user = u.id_user
      AND existing.id_scope = s.id_scope
      AND existing.reason = 'legacy users read access'
);

INSERT INTO user_scope_grants (id_user, id_scope, reason)
SELECT u.id_user, s.id_scope, 'legacy users write access'
FROM users u
JOIN users_modules um ON um.id_user = u.id_user
JOIN modules m ON m.id_module = um.id_module AND m.name = 'USERS'
JOIN users_submodules us ON us.id_user = u.id_user
JOIN submodules sm ON sm.id_submodule = us.id_submodule AND sm.name = 'WRITEUSERS'
JOIN scopes s ON s.name IN ('user:create', 'user:update', 'user:delete')
WHERE NOT EXISTS (
    SELECT 1
    FROM user_scope_grants existing
    WHERE existing.id_user = u.id_user
      AND existing.id_scope = s.id_scope
      AND existing.reason = 'legacy users write access'
);

INSERT INTO user_scope_grants (id_user, id_scope, reason)
SELECT u.id_user, s.id_scope, 'legacy perfumes read access'
FROM users u
JOIN users_modules um ON um.id_user = u.id_user
JOIN modules m ON m.id_module = um.id_module AND m.name = 'PERFUMES'
JOIN users_submodules us ON us.id_user = u.id_user
JOIN submodules sm ON sm.id_submodule = us.id_submodule AND sm.name = 'READPERFUMES'
JOIN scopes s ON s.name = 'perfume:read'
WHERE NOT EXISTS (
    SELECT 1
    FROM user_scope_grants existing
    WHERE existing.id_user = u.id_user
      AND existing.id_scope = s.id_scope
      AND existing.reason = 'legacy perfumes read access'
);

INSERT INTO user_scope_grants (id_user, id_scope, reason)
SELECT u.id_user, s.id_scope, 'legacy perfumes write access'
FROM users u
JOIN users_modules um ON um.id_user = u.id_user
JOIN modules m ON m.id_module = um.id_module AND m.name = 'PERFUMES'
JOIN users_submodules us ON us.id_user = u.id_user
JOIN submodules sm ON sm.id_submodule = us.id_submodule AND sm.name = 'WRITEPERFUMES'
JOIN scopes s ON s.name IN ('perfume:create', 'perfume:update', 'perfume:delete')
WHERE NOT EXISTS (
    SELECT 1
    FROM user_scope_grants existing
    WHERE existing.id_user = u.id_user
      AND existing.id_scope = s.id_scope
      AND existing.reason = 'legacy perfumes write access'
);
